### ISSUE TITLE
Add maven

### ISSUE THREAD

**Issue by nsporillo** [RathelmMC/MC-Jobs#2]
Open source is great, but for Java projects that have dependencies like all Bukkit/Spigot plugins do, it's nice to have maven so we don't need to use Eclipse and add jars to our build path. IDE interoperability is always nice to have.

I can fork and convert the project to maven and then PR that if you'd like.

**Comment by GeigerCounter** [comment]
I agree with you. In fact, I'm forking the project now to add Maven support, Spigot/New Bukkit compatibility ( in particular, fixing an issue with getonlineplayers() ) and possibly incorporate more actions as jobs. If it's good enough, I'll PR it. If not or if my PR gets rejected, at very least I can keep hosting it opensource.
