### ISSUE TITLE
# of Jobs per Rank not working

### ISSUE THREAD

**Issue by ghost** [RathelmMC/MC-Jobs#5]
My current config.yml  for reference - http://hastebin.com/uniloxamor.sm

If you noticed, I have 5 ranks - default, veteran, vip , mod, and admin.

Each rank has different # of jobs that they can join. I noticed that it's not working on my server. The only one that is implemented was that of the default, which allow players to take 4 jobs.

May I know how to fix this pls? I am using GroupManager for my permissions.

**Comment by PiggiesGoSqueal** [comment]
I realize this post is outdated and it likely will never get fixed. But if anyone plans to update this plugin, I am having the same issue on Spigot 1.12.2 with LuckPerms.
